### ISSUE TITLE
Feature: add github webhook for automating RPM builds with Copr

### ISSUE THREAD

**Issue by xsnrg** [knro/ekosdebugger#2]
Here is the `application/json` webhook URL to add to github knro/ekosdebugger repo to automate the creating of RPM packages for ekosdebugger:

`https://copr.fedorainfracloud.org/webhooks/github/34058/986d9100-f3d8-433c-9f77-c3b42201fb4d/ `

**Comment by knro** [comment]
Thanks! It's done.

**Comment by xsnrg** [comment]
and works! https://copr.fedorainfracloud.org/coprs/xsnrg/ekosdebugger/builds/
